#include "./headerFiles/db.h"

Database data = {{{0, "Australian Bass", {}, false},
                  {1, "Estuary Perch", {}, false},
                  {2, "Australian Salmon", {}, false},
                  {3, "Blue Drummer", {}, false},
                  {4, "Bonito", {}, false},
                  {5, "Bream (Black/Southern)", {25, -1}, false},
                  {6, "Bream (Yellowfin)", {25, -1}, false},
                  {7, "Tarwhine", {20, -1}, false},
                  {8, "Cobia", {}, false},
                  {9, "Hapuku (Hapuka)", {}, false},
                  {10, "Banded Rock Cod (Bar Cod)", {}, false},
                  {11, "Bass Groper", {}, false},
                  {12, "Gemfish", {}, false},
                  {13, "Blue-Eye Trevalla (Cod)", {}, false},
                  {14, "Dogfish (Harrisson's)", {}, false},
                  {15, "Dogfish (Southern)", {}, false},
                  {16, "Dogfish (All other)", {}, false},
                  {17, "Eastern Blue Groper", {}, false},
                  {18, "Mahi Mahi (Dolphinfish)", {60, -1}, false},
                  {19, "Eel (Southern Shortfin)", {30, -1}, false},
                  {20, "Eel (Longfin)", {58, -1}, false},
                  {21, "Flathead (Dusky)", {36, 70}, false},
                  {22, "Flathead (Bluespotted)", {33, -1}, false},
                  {23, "Flathead (Tiger)", {33, -1}, false},
                  {24, "Flounder", {25, -1}, false},
                  {25, "Sole", {}, false},
                  {26, "Garfish (Eastern Sea)", {}, false},
                  {27, "Hairtail", {}, false},
                  {28, "Leatherjacket", {}, false},
                  {29, "Luderick", {27, -1}, false},
                  {30, "Mackerel (Spanish)", {75, -1}, false},
                  {31, "Mackerel (Spotted)", {60, -1}, false},
                  {32, "Mangrove Jack", {}, false},
                  {33, "Marlin (Striped)", {}, false},
                  {34, "Marlin (Black)", {}, false},
                  {35, "Marlin (Blue)", {}, false},
                  {36, "Morwong (Grey/Rubberlip)", {30, -1}, false},
                  {37, "Morwong (Jackass)", {30, -1}, false},
                  {38, "Morwong (Red)", {30, -1}, false},
                  {39, "Morwong (Banded)", {}, false},
                  {40, "Moses Snapper (Moses Perch)", {}, false},
                  {41, "Mullet (Poddy/Small)", {0, 15}, false},
                  {42, "Mullet (Sea/Bully)", {30, -1}, false},
                  {43, "Mulloway", {70, -1}, false},
                  {44, "Pearl Perch", {30, -1}, false},
                  {45, "Eastern Red Scorpionfish (Red Rock Cod)", {}, false},
                  {46, "Rock Blackfish (Black Drummer)", {30, -1}, false},
                  {47, "Sailfish", {}, false},
                  {48, "Samsonfish", {}, false},
                  {49, "Amberjack", {}, false},
                  {50, "Australian Sawtail", {}, false},
                  {51, "Shark (Wobbegong)", {}, false},
                  {52, "Shark (Mako)", {}, false},
                  {53, "Shark (School)", {91, -1}, false},
                  {54, "Shark (Whaler)", {}, false},
                  {55, "Snapper", {30, -1}, false},
                  {56, "Spearfish (Shortbill)", {}, false},
                  {57, "Swordfish", {}, false},
                  {58, "Tailor", {30, -1}, false},
                  {59, "Teraglin", {38, -1}, false},
                  {60, "Trevallies (Silver Trevally)", {30, -1}, false},
                  {61, "Trevallies (all other)", {}, false},
                  {62, "Tuna (Albacore)", {90, -1}, false},
                  {63, "Tuna (Bigeye)", {90, -1}, false},
                  {64, "Tuna (Longtail)", {90, -1}, false},
                  {65, "Tuna (Yellowfin)", {90, -1}, false},
                  {66, "Tuna (Southern Bluefin)", {}, false},
                  {67, "Wahoo", {}, false},
                  {68, "Whiting (Sand)", {27, -1}, false},
                  {69, "Yellowtail Kingfish", {65, -1}, false}},
                 {{70, "Abalone", {11.7, -1}, false},
                  {71, "Balmain Bug", {10, -1}, true},
                  {72, "Beach Worms", {}, false},
                  {73, "All other worms", {}, false},
                  {74, "Cockles", {}, false},
                  {75, "Mussels", {}, false},
                  {76, "Pipis", {}, false},
                  {77, "Crab (Blue Swimmer)", {6.5, -1}, true},
                  {78, "Crab (Mud)", {8.5, -1}, true},
                  {79, "Crab (Spanner)", {9.3, -1}, true},
                  {80, "Crab (Soldier)", {}, true},
                  {81, "All other crabs", {}, true},
                  {82, "Cunjevoi", {}, false},
                  {83, "Lobster (Eastern Rock)", {10.4, 18}, true},
                  {84, "Lobster (Southern Rock) male", {11, -1}, true},
                  {85, "Lobster (Southern Rock) female", {10.5, -1}, true},
                  {86, "Tropical Rock Lobster (Painted and Ornate)", {}, true},
                  {87, "Slipper Lobster (Flat)", {}, true},
                  {88, "Octopus", {}, false},
                  {89, "Oysters (Sydney Rock, Pacific, Native)", {}, false},
                  {90, "Prawns", {}, false},
                  {91, "Saltwater Nippers", {}, false},
                  {92, "Scallops", {}, false},
                  {93, "Sea Urchins", {}, false},
                  {94, "Squid & Cuttlefish", {}, false},
                  {95, "Turban Snails (Sydney, Military)", {7.5, -1}, false},
                  {96, "Turban Snails (all other molluscs)", {}, false}}};