#include "./headerFiles/db.h"

Database data = {
    {
        {0, "Bass & Perch",         2},
        {1, "Bream & Tarwhine",     10},
        {2, "Flathead (non-Dusky)", 10},
        {3, "Trevallies",           10},
        {4, "Tuna",           2},
        {5, "Samson & Amberjack",           5},
        {6, "Sharks & Rays",        5},
        {7, "Rock Lobster",         3},
        {8, "Deep-sea fish",         5},
        {9, "Flounder & Sole",         20},
        {10, "Mackerel",         5},
        {11, "Cockles, Mussels and Pipis",         50},
    },
 
    {
        {0,  "Australian Bass",                        {},        false,  2,   0},
        {1,  "Estuary Perch",                          {},        false,  2,   0},
        {2,  "Australian Salmon",                      {},        false, 5,  -1},
        {3,  "Blue Drummer",                           {},        false, 0,  -1},
        {4,  "Bonito",                                 {},        false, 10,  -1},
        {5,  "Bream (Black/Southern)",                 {25, -1},  false, 10,   1},
        {6,  "Bream (Yellowfin)",                      {25, -1},  false, 10,   1},
        {7,  "Tarwhine",                               {20, -1},  false, 10,   1},
        {8,  "Cobia",                                  {},        false, 5,  -1},
        {9,  "Hapuku (Hapuka)",                        {},        false, -1,  8},
        {10, "Banded Rock Cod (Bar Cod)",              {},        false, -1,  8},
        {11, "Bass Groper",                            {},        false, -1,  8},
        {12, "Gemfish",                                {},        false,  2,  8},  
        {13, "Blue-Eye Trevalla (Cod)",                {},        false, -1,  8},
        {14, "Dogfish (Harrisson's)",                  {},        false, 0,  -1},
        {15, "Dogfish (Southern)",                     {},        false, 0,  -1},
        {16, "Dogfish (All other)",                    {},        false, 2,  -1},
        {17, "Eastern Blue Groper",                    {},        false,  0,  -1},  
        {18, "Mahi Mahi (Dolphinfish)",                {60, -1},  false, 10,  -1},
        {19, "Eel (Southern Shortfin)",                {30, -1},  false, 10,  -1},
        {20, "Eel (Longfin)",                          {58, -1},  false, 10,  -1},
        {21, "Flathead (Dusky)",                       {36, 70},  false, 5,  -1},  
        {22, "Flathead (Bluespotted)",                 {33, -1},  false, 10,   2},
        {23, "Flathead (Tiger)",                       {33, -1},  false, 10,   2},
        {24, "Flounder",                               {25, -1},  false, -1,  9},
        {25, "Sole",                                   {},        false, -1,  9},
        {26, "Garfish (Eastern Sea)",                  {},        false, -1,  -1},
        {27, "Hairtail",                               {},        false, 10,  -1},
        {28, "Leatherjacket",                          {},        false, -1,  -1},
        {29, "Luderick",                               {27, -1},  false, 10,  -1},
        {30, "Mackerel (Spanish)",                     {75, -1},  false, -1,  10},
        {31, "Mackerel (Spotted)",                     {60, -1},  false, -1,  10},
        {32, "Mangrove Jack",                          {},        false, 5,  -1},
        {33, "Marlin (Striped)",                       {},        false,  1,  -1},
        {34, "Marlin (Black)",                         {},        false,  1,  -1},
        {35, "Marlin (Blue)",                          {},        false,  1,  -1},
        {36, "Morwong (Grey/Rubberlip)",               {30, -1},  false, 10,  -1},
        {37, "Morwong (Jackass)",                      {30, -1},  false, 10,  -1},
        {38, "Morwong (Red)",                          {30, -1},  false, 5,  -1},
        {39, "Morwong (Banded)",                       {},        false, 5,  -1},
        {40, "Moses Snapper (Moses Perch)",            {},        false, 5,  -1},
        {41, "Mullet (Poddy/Small)",                   {0, 15},   false, -1,  -1},
        {42, "Mullet (Sea/Bully)",                     {30, -1},  false, -1,  -1},
        {43, "Mulloway",                               {70, -1},  false,  1,  -1},  
        {44, "Pearl Perch",                            {30, -1},  false, 5,  -1},
        {45, "Eastern Red Scorpionfish (Red Rock Cod)",{},        false, 5,  -1},
        {46, "Rock Blackfish (Black Drummer)",         {30, -1},  false, 10,  -1},
        {47, "Sailfish",                               {},        false,  1, -1},
        {48, "Samsonfish",                             {},        false, 5,  5},
        {49, "Amberjack",                              {},        false, 5,  5},
        {50, "Australian Sawtail",                     {},        false, 5,  -1},
        {51, "Shark (Wobbegong)",                      {},        false,  0,   -1},
        {52, "Shark (Mako)",                           {},        false,  1,   6},
        {53, "Shark (School)",                         {91, -1},  false, -1,   6},
        {54, "Shark (Whaler)",                         {},        false,  1,   6},
        {55, "Snapper",                                {30, -1},  false, 10,  -1},
        {56, "Spearfish (Shortbill)",                  {},        false,  1,   -1},
        {57, "Swordfish",                              {},        false,  1,   -1},
        {58, "Tailor",                                 {30, -1},  false, 10,  -1},
        {59, "Teraglin",                               {38, -1},  false, 5,  -1},
        {60, "Trevallies (Silver Trevally)",           {30, -1},  false, 10,   3},
        {61, "Trevallies (all other)",                 {},        false, 10,   3},
        {62, "Tuna (Albacore)",                        {90, -1},  false, -1,  4},
        {63, "Tuna (Bigeye)",                          {90, -1},  false, -1,  4},
        {64, "Tuna (Longtail)",                        {90, -1},  false, -1,  4},
        {65, "Tuna (Yellowfin)",                       {90, -1},  false, -1,  4},
        {66, "Tuna (Southern Bluefin)",                {},        false, 1,  -1},
        {67, "Wahoo",                                  {},        false, 5,  -1},
        {68, "Whiting (Sand)",                         {27, -1},  false, -1,  -1},
        {69, "Yellowtail Kingfish",                    {65, -1},  false, 5,  -1},
    },
 
    {
        {70, "Abalone",                                      {11.7, -1}, false,  2,  -1},
        {71, "Balmain Bug",                                  {10, -1},   true,  -1,  -1},
        {72, "Beach Worms",                                  {},         false, -1,  -1},
        {73, "All other worms",                              {},         false, 100,  -1},
        {74, "Cockles",                                      {},         false, 20, 11},
        {75, "Mussels",                                      {},         false, -1, 11},
        {76, "Pipis",                                        {},         false, -1, 11},
        {77, "Crab (Blue Swimmer)",                          {6.5, -1},  true,  10,  -1},
        {78, "Crab (Mud)",                                   {8.5, -1},  true,  5,  -1},
        {79, "Crab (Spanner)",                               {9.3, -1},  true,  10,  -1},
        {80, "Crab (Soldier)",                               {},         true,  100,  -1},
        {81, "All other crabs",                              {},         true,  10,  -1},
        {82, "Cunjevoi",                                     {},         false, -1,  -1},
        {83, "Lobster (Eastern Rock)",                       {10.4, 18}, true,   2,   7},
        {84, "Lobster (Southern Rock) male",                 {11, -1},   true,   2,   7},
        {85, "Lobster (Southern Rock) female",               {10.5, -1}, true,   2,   7},
        {86, "Tropical Rock Lobster (Painted and Ornate)",   {},         true,  2,  -1},
        {87, "Slipper Lobster (Flat)",                       {},         true,  2,  -1},
        {88, "Octopus",                                      {},         false, 10,  -1},
        {89, "Oysters (Sydney Rock, Pacific, Native)",       {},         false, 50,  -1},
        {90, "Prawns",                                       {},         false, 10,  -1},
        {91, "Saltwater Nippers",                            {},         false, 100,  -1},
        {92, "Scallops",                                     {},         false, 50,  -1},
        {93, "Sea Urchins",                                  {},         false, 10,  -1},
        {94, "Squid & Cuttlefish",                           {},         false, -1,  -1},
        {95, "Turban Snails (Sydney, Military)",             {7.5, -1},  false, -1,  -1},
        {96, "Turban Snails (all other molluscs)",           {},         false, -1,  -1},
    }
};